version: '3'
services: 
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pass
  
  dawllapop:
    image: daniribeiro/shoppaholic
    depends_on:
      - mysql
    ports:
      - 8443:8443
    links:
      - mysql:mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost/test?useSSL=false