version: '3'
services:
  mysql:
    image: mysql:5.7
  # container_name: mysql-spring
    container_name: mysql-springShoppaholic
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=test
# spring-repository:
  spring-repositoryShoppaholic:
    depends_on:
      - mysql
    image: pmorenoyurjc/shoppaholic:latest
  # container_name: springbackend
    container_name: springbackendShoppaholic
    ports:
    # - 8443:8443
      - 8443:8443
    links:
      - mysql:mysql
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test
